language: scala
scala:
- 2.13.1
jdk:
- openjdk8
script:
- sbt test

before_install:
- if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then
     openssl aes-256-cbc -K $encrypted_00c350792894_key -iv $encrypted_00c350792894_iv -in secring.gpg.enc -out secring.gpg -d;
  fi

after_success:
- if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then
     sbt compile publishSigned;
  fi
